# Generated by Django 3.1.6 on 2021-02-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210218_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='foto_publicacao',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_publicacoes', verbose_name='Foto Publicação'),
        ),
    ]
