# Generated by Django 2.2.13 on 2021-02-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210220_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='foto_publicacao',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/noticias', verbose_name='Foto Publicação'),
        ),
    ]
